[tools]
"gem:bundler" = "latest"
"gem:neovim" = "latest"
"gem:rubocop" = "latest"
"gem:ruby-lsp" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@modelcontextprotocol/inspector" = "latest"
"npm:@openai/codex" = "latest"
"npm:neovim" = "latest"
"npm:sql-formatter" = "latest"
go = "1.25"
node = "22"
ruby = "3.4"
"npm:@github/copilot" = "latest"
python = "3.12"
uv = "latest"
"pipx:serena-agent" = "latest"
"npm:@devcontainers/cli" = "latest"
bun = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "ruby", "go", "python"]
